docker stop shipyard-controller
docker rm shipyard-controller
docker stop shipyard-swarm-agent
docker rm shipyard-swarm-agent
docker stop shipyard-swarm-manager
docker rm shipyard-swarm-manager
docker stop shipyard-proxy
docker rm shipyard-proxy
docker stop shipyard-certs
docker rm shipyard-certs
docker stop shipyard-discovery
docker rm shipyard-discovery
docker stop shipyard-rethinkdb
docker rm shipyard-rethinkdb
